Vagrant.configure("2") do |config|
 config.vm.define :firewall do |firewall|
 firewall.vm.box = "bento/centos-7"
 firewall.vm.network :private_network, ip: "192.168.100.5"
 firewall.vm.network "public_network", use_dhcp_assigned_default_route: true
 firewall.vm.hostname = "firewall"
 end
 config.vm.define :servidorftp do |servidorftp|
 servidorftp.vm.box = "bento/centos-7"
 servidorftp.vm.network :private_network, ip: "192.168.100.6"
 servidorftp.vm.network :forwarded_port, guest: 80, host:5567
 servidorftp.vm.hostname = "servidorftp"
 end
end
